# Generated by Django 5.2.3 on 2025-07-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0012_calificacion_es_recuperada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='firma_rector',
            field=models.ImageField(blank=True, help_text='Imagen de la firma para los reportes', null=True, upload_to='firmas_rectores/', verbose_name='Firma del Rector(a)'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='nombre_rector',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Completo del Rector(a)'),
        ),
    ]
