# Generated by Django 5.2.3 on 2025-08-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0013_colegio_firma_rector_colegio_nombre_rector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['orden'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='curso',
            name='orden',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
