# Generated by Django 5.2.3 on 2026-03-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0014_alter_curso_options_curso_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodoacademico',
            name='ano_lectivo',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
