# Generated by Django 5.2.3 on 2026-04-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0015_alter_periodoacademico_ano_lectivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='fuente_firma_rector',
            field=models.CharField(choices=[('Helvetica', 'Helvetica (Estándar)'), ('Arial', 'Arial'), ('Times New Roman', 'Times New Roman'), ('Courier', 'Courier (Máquina de escribir)'), ('Verdana', 'Verdana'), ('Georgia', 'Georgia'), ('Garamond', 'Garamond'), ('Game On_PersonalUseOnly', 'Game On (Personalizada)')], default='Helvetica', max_length=100, verbose_name='Fuente de la Firma del Rector'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='mostrar_firma_rector_boletin',
            field=models.BooleanField(default=False, verbose_name='Mostrar Firma del Rector en Boletines'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='mostrar_foto_estudiante_boletin',
            field=models.BooleanField(default=False, verbose_name='Mostrar Foto del Estudiante en Boletines'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='tamano_firma_rector',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Tamaño de Letra del Rector (pt)'),
        ),
    ]
