# Generated by Django 5.2.3 on 2026-04-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0016_colegio_fuente_firma_rector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='formatear_logros_automatico',
            field=models.BooleanField(default=True, help_text='Si se desactiva, el logro se mostrará exactamente como lo escribió el docente. Si se activa, se convertirá a minúsculas y se le añadirá un prefijo de coherencia.', verbose_name='Formatear logros automáticamente'),
        ),
    ]
