# Generated by Django 5.2.3 on 2026-04-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0017_colegio_formatear_logros_automatico'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='tamano_letra_boletin',
            field=models.PositiveSmallIntegerField(default=9, help_text='Ajusta el tamaño del texto general de los boletines (Recomendado: 8 o 9).', verbose_name='Tamaño de Letra General (px)'),
        ),
    ]
