# Generated by Django 5.2.3 on 2026-04-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0018_colegio_tamano_letra_boletin'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='observacion_inclusion',
            field=models.TextField(blank=True, help_text='Indicador personalizado para estudiantes de inclusión', null=True, verbose_name='Indicador de Inclusión'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='es_inclusion',
            field=models.BooleanField(default=False, help_text='Marcar si el estudiante pertenece al programa de inclusión. Se ignorará para rankings.', verbose_name='Estudiante de Inclusión'),
        ),
    ]
