# Generated by Django 5.2.3 on 2026-04-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0019_calificacion_observacion_inclusion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='etiqueta_hacer',
            field=models.CharField(default='HACER', max_length=30, verbose_name='Nombre Componente 3 (Hacer)'),
        ),
        migrations.AddField(
            model_name='materia',
            name='etiqueta_saber',
            field=models.CharField(default='SABER', max_length=30, verbose_name='Nombre Componente 2 (Saber)'),
        ),
        migrations.AddField(
            model_name='materia',
            name='etiqueta_ser',
            field=models.CharField(default='SER', max_length=30, verbose_name='Nombre Componente 1 (Ser)'),
        ),
        migrations.AddField(
            model_name='materia',
            name='promedia_en_boletin',
            field=models.BooleanField(default=True, help_text='Si se desmarca, no sumará al promedio general.', verbose_name='¿Promedia en el Boletín?'),
        ),
    ]
