# Generated by Django 5.2.3 on 2026-05-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0020_materia_etiqueta_hacer_materia_etiqueta_saber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='alto_logos_pdf',
            field=models.PositiveSmallIntegerField(default=65, verbose_name='Altura Máxima de Logos en PDF (px)'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='color_fondo',
            field=models.CharField(default='#F8F9FA', max_length=7),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='color_texto_primario',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='encabezado_pdf_sin_bordes',
            field=models.BooleanField(default=False, verbose_name='Quitar bordes del encabezado en PDF'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='escudo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_colegios/', verbose_name='Logo/Escudo Principal del Portal'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='logos_colegios/'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='firma_rector',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_rectores/', verbose_name='Firma del Rector(a)'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='formatear_logros_automatico',
            field=models.BooleanField(default=True, verbose_name='Formatear logros automáticamente'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='logo_derecho',
            field=models.ImageField(blank=True, null=True, upload_to='logos_colegios/', verbose_name='Logo Derecho (Reportes)'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='logo_izquierdo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_colegios/', verbose_name='Logo Izquierdo (Reportes)'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='tamano_letra_boletin',
            field=models.PositiveSmallIntegerField(default=9, verbose_name='Tamaño de Letra General (px)'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='whatsapp_numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número de WhatsApp'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='es_inclusion',
            field=models.BooleanField(default=False, help_text='Se ignorará para rankings.', verbose_name='Estudiante de Inclusión'),
        ),
    ]
