# Generated by Django 5.2.3 on 2026-05-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0021_alter_colegio_alto_logos_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='alto_logos_pdf',
            field=models.PositiveSmallIntegerField(default=65, help_text='Ajusta la altura de los logos para que se alineen con el texto del encabezado.', verbose_name='Altura Máxima de Logos en PDF (px)'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='color_fondo',
            field=models.CharField(default='#F8F9FA', help_text='Color de fondo general de las páginas', max_length=7),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='color_texto_primario',
            field=models.CharField(default='#FFFFFF', help_text='Color del texto sobre el color primario (ej. en botones)', max_length=7),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='encabezado_pdf_sin_bordes',
            field=models.BooleanField(default=False, help_text='Marcar si el encabezado debe ocupar todo el ancho sin bordes (diseño especial).', verbose_name='Quitar bordes del encabezado en PDF'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='escudo',
            field=models.ImageField(blank=True, help_text='Escudo para el portal y marca de agua en PDFs', null=True, upload_to='logos_colegios/', verbose_name='Logo/Escudo Principal del Portal'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Icono para la pestaña del navegador (32x32px)', null=True, upload_to='logos_colegios/'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='firma_rector',
            field=models.ImageField(blank=True, help_text='Imagen de la firma para los reportes', null=True, upload_to='firmas_rectores/', verbose_name='Firma del Rector(a)'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='formatear_logros_automatico',
            field=models.BooleanField(default=True, help_text='Si se desactiva, el logro se mostrará exactamente como lo escribió el docente. Si se activa, se convertirá a minúsculas y se le añadirá un prefijo de coherencia.', verbose_name='Formatear logros automáticamente'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='logo_derecho',
            field=models.ImageField(blank=True, help_text='Ej: Logo de la Gobernación', null=True, upload_to='logos_colegios/', verbose_name='Logo Derecho (Reportes)'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='logo_izquierdo',
            field=models.ImageField(blank=True, help_text='Ej: Logo del Colegio', null=True, upload_to='logos_colegios/', verbose_name='Logo Izquierdo (Reportes)'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='tamano_letra_boletin',
            field=models.PositiveSmallIntegerField(default=9, help_text='Ajusta el tamaño del texto general de los boletines (Recomendado: 8 o 9).', verbose_name='Tamaño de Letra General (px)'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='whatsapp_numero',
            field=models.CharField(blank=True, help_text='Incluir código de país, ej: 573001234567', max_length=20, verbose_name='Número de WhatsApp'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='es_inclusion',
            field=models.BooleanField(default=False, help_text='Marcar si el estudiante pertenece al programa de inclusión. Se ignorará para rankings.', verbose_name='Estudiante de Inclusión'),
        ),
    ]
