# Generated by Django 5.2.3 on 2026-03-02 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('CAMARA', 'Cámara de Representantes'), ('SENADO', 'Senado de la República'), ('CONSULTA', 'Consulta Presidencial')], max_length=20)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('siglas', models.CharField(blank=True, max_length=10)),
                ('logo_color', models.CharField(default='#cccccc', help_text='Color HEX para las gráficas', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PuestoVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('departamento', models.CharField(default='Tolima', max_length=100)),
                ('municipio', models.CharField(default='Honda', max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeton', models.IntegerField(blank=True, help_text="Dejar en blanco si es voto 'Solo por el partido' o lista cerrada", null=True)),
                ('nombre', models.CharField(blank=True, help_text='Opcional. Para cámara/senado suele bastar con el número', max_length=200)),
                ('corporacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.corporacion')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.partido')),
            ],
            options={
                'ordering': ['partido', 'numero_tarjeton'],
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mesa', models.IntegerField()),
                ('total_sufragantes', models.IntegerField(default=0, help_text='Total de personas que votaron según formulario E-11')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='elecciones.puestovotacion')),
            ],
            options={
                'ordering': ['puesto', 'numero_mesa'],
                'unique_together': {('puesto', 'numero_mesa')},
            },
        ),
        migrations.CreateModel(
            name='FichaEscrutinio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votos_en_blanco', models.IntegerField(default=0)),
                ('votos_nulos', models.IntegerField(default=0)),
                ('votos_no_marcados', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('esta_validada', models.BooleanField(default=False, help_text='True si el SuperAdmin ya revisó que no hay descuadres')),
                ('corporacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.corporacion')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.mesa')),
            ],
            options={
                'unique_together': {('mesa', 'corporacion')},
            },
        ),
        migrations.CreateModel(
            name='DetalleVoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.candidato')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_detalle', to='elecciones.fichaescrutinio')),
            ],
            options={
                'unique_together': {('ficha', 'candidato')},
            },
        ),
    ]
