# Generated by Django 5.2.3 on 2026-03-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='logo',
            field=models.ImageField(blank=True, help_text='Sube el logo oficial del partido (Opcional)', null=True, upload_to='logos_partidos/'),
        ),
    ]
